$(function(){
	//--
	$('.indexIndications').find('li:first').addClass('liNow');
	$('.idea').find('li:last').css('background','none');
	$('.clinical').find('.tabContent').find('li:last').css('border',0);
	$('.brand1').find('li:last').css('border',0);
	$('.job').find('li:last').css('background','none');
	//--
	$('.sNavA').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNav').eq(i).css('top',$(this).offset().top+50);
			   $('.sNav').eq(i).css('left',$(this).offset().left-25);
			   $('.sNav').eq(i).show();
			   },
		   function(){
			   $('.sNav').eq(i).hide();
			   }
		)
		})	
	$('.sNav').each(function(i){
		$(this).hover(
		   function(){
			   $('.sNavA').eq(i).addClass('sNavANow');
			   $(this).show();
			   },
		   function(){
			   $('.sNavA').eq(i).removeClass('sNavANow');
			   $(this).hide();
			   }
		)
		})
	$('.sNav').find('li').hover(
	    function(){
			$(this).find('a:first').addClass('aNow');
			$(this).find('div:first').show();
			},
		function(){
			$(this).find('a:first').removeClass('aNow');
			$(this).find('div:first').hide();
			}
	)	
	//--
	/*var indexIndicationsNow=0;
	$('.indexIndications').find('li').each(function(i){
		$(this).click(
		   function(){
			   $('.indexIndications').find('li').eq(indexIndicationsNow).find('.imgDiv').animate({height: 0}, 300);
			   indexIndicationsNow=i;
			   $('.indexIndications').find('li').eq(indexIndicationsNow).find('.imgDiv').animate({height: 95}, 300);
			   }
		)
	})*/
	//--
	$('.honor').find('li:last').addClass('liLast');
	//--
	var indexProductTime;
	if($('.indexProduct').length>0){
		$('.indexProduct').find('.list').find('ul').html($('.indexProduct').find('.list').find('ul').html()+$('.indexProduct').find('.list').find('ul').html());
		indexProductWidth=$('.indexProduct').find('.list').find('li').length/2*194;
		indexProductTime=setInterval('indexProductFun()',20);
		}	
	$('.indexProduct').hover(
	    function(){
			clearInterval(indexProductTime);
			},
		function(){
			indexProductTime=setInterval('indexProductFun()',20);
			}
	)	
	$('.indexProduct').find('.rightBtn').click(function(){
		if(indexProductScroll<indexProductWidth){
		indexProductScroll=indexProductScroll+194;
		}
		$('.indexProduct').find('.list').animate({scrollLeft: indexProductScroll}, 200);
		})
	$('.indexProduct').find('.leftBtn').click(function(){
		if(indexProductScroll>0){
		indexProductScroll=indexProductScroll-194;
		}
		$('.indexProduct').find('.list').animate({scrollLeft: indexProductScroll}, 200);
		})
	/*$('.indexProduct').find('.rightBtn').click(function(){
		imgScrollRight2($('.indexProduct').find('.list'),$('.indexProduct').find('li').length-3,194,0);
		})
	$('.indexProduct').find('.leftBtn').click(function(){
		imgScrollLeft2($('.indexProduct').find('.list'),$('.indexProduct').find('li').length-3,194,0);
		})	*/
	$('.indexProduct').find('li').find('img:first').hide();	
	$('.indexProduct').find('li').find('img:last').show();	
	$('.indexProduct').find('li').hover(
	    function(){
			$(this).addClass('liNow');
			},
		function(){
			$(this).removeClass('liNow');
			}
	)	
	//--
	$('.productTab').find('li:last').css('background','none');
	$('.productTab').find('li').click(function(){
		$('.productTab').find('li').removeClass('liNow');
		$(this).addClass('liNow');
		})
	//--
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}	
				)
			})
		})	
	//--
	$('.productShowPart1').find('tr:last').find('td').css('border-bottom','0px');	
	//--
	$('.caseDiv1').find('.list').find('li:last').css('border','0px');
	//--
	$('.brand1').find('li').each(function(i){
		$(this).find('.btn').toggle(
		   function(){
			   $('.brand1').find('li').eq(i).find('.contentDiv').show();
			   },
		   function(){
			   $('.brand1').find('li').eq(i).find('.contentDiv').hide();
			   }
		)
		})
	//--
	var jobNow=1000;
	$('.job').find('li').each(function(i){
		$(this).find('.time').click(function(){
			$('.job').find('li').find('.time').removeClass('timeNow');
			$('.job').find('li').find('.contentDiv').hide();
			if(jobNow==i){
				jobNow=100;
				}else{
					jobNow=i;
					$(this).addClass('timeNow');
					$('.job').find('li').find('.contentDiv').eq(i).show();
					}
			})
		})	
	//--
	var fadeFlashTime=new Array();
	$('.fadeFlash').find('li:first').fadeIn(500);
	$('.fadeFlash').each(function(i){
		fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
		$(this).find('.btnDiv').find('span').each(function(ii){
			$(this).hover(
			function(){
				clearInterval(fadeFlashTime[i]);
				$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
				$(this).addClass('spanNow');
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(1000);
				fadeFlashNow[i]=ii;
				$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(1000);
				fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
				},
			function(){}	
				)
			})
		$(this).find('.rightBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(1000);
			if(fadeFlashNow[i]<$('.fadeFlash').eq(i).find('li').length-1){
				fadeFlashNow[i]++;
				}else{
					fadeFlashNow[i]=0;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(1000);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		$(this).find('.leftBtn').click(function(){
			clearInterval(fadeFlashTime[i]);
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').removeClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeOut(1000);
			if(fadeFlashNow[i]>0){
				fadeFlashNow[i]--;
				}else{
					fadeFlashNow[i]=$('.fadeFlash').eq(i).find('li').length-1;
					}
			$('.fadeFlash').eq(i).find('.btnDiv').find('span').eq(fadeFlashNow[i]).addClass('spanNow');
			$('.fadeFlash').eq(i).find('li').eq(fadeFlashNow[i]).fadeIn(1000);
			fadeFlashTime[i] = setInterval("fadeFlashFun("+i+")",5000);
			})	
		})	
	//--
	$('.topList').find('.a1').click(function(){
		$('.loginLayer').css('left',$(this).offset().left-317);
		$('.loginLayer').css('top',$(this).offset().top+30);
		$('.loginLayer').show();
		})	
	$('.loginLayer').hover(
	    function(){},
		function(){
			$(this).hide();
			}
	)	
	//--
	if($('.headDiv2').length>0){
		$('.topList').find('li').eq(1).hide();
		}
	//--
	$('#fenye').hide();
	$('.pageNum').html($('#fenye').find('#pagelist').html()+"<span>|　共"+$('#fenye').find('#totalpage').html()+"页</span>");
	$('.pageNum').find('a').each(function(i){
		if($(this).find('font').length>0){
			$(this).addClass('aNow');
			$(this).html($(this).find('font').html());
			}
		$(this).html($(this).html().substr(1,1));
		})
	//--
	if($('#video').length>0){
		var src="http://accu.kt85.com/"+$('#video').attr('src');
		var img="http://accu.kt85.com/"+$('#video').attr('img');
		createflash2(src,img);
		}	
	//--
	$('.productMLHC').find('li').each(function(i){
		if(i%3==0){
			$(this).addClass('li_01');
			}
		})	
	//
	})